Import('env')

env = env.Clone()
env.Append(CPPFLAGS=['-Wall', '-fmessage-length=0', '-std=c++1z', '-O3', '-ftemplate-depth=100000'])
env.VariantDir('build', 'src', duplicate=False)

env.Program(target='build/std.out', source='build/std.cpp')
env.Program(target='build/list.out', source='build/list.cpp')
env.Program(target='build/match.out', source='build/match.cpp')
env.Program(target='build/lambda.out', source='build/lambda.cpp')

env.Program(target='build/math.out', source='build/math.cpp')
env.Program(target='build/maybe.out', source='build/maybe.cpp')
env.Program(target='build/set.out', source='build/set.cpp')
env.Program(target='build/lazy.out', source='build/lazy.cpp')
env.Program(target='build/lambda.out', source='build/lambda.cpp')
