Import('env')

env = env.Clone()
env.Append(CPPFLAGS=['-g', '-Wall', '-fmessage-length=0', '-std=c++1y'])
env.VariantDir('build', 'src', duplicate=0)

env.Program(target='build/main.out', source = 'build/main.cpp')
